/* Calculadora Comercial Multisserviços - GitHub Pages
   Leitura Google Sheets CSV + catálogo local + orçamento/PDF por impressão + QR Code.
*/
const SHEET_ID='18hBRKP0iEKiRgCRkICcTgWFCTougR_HcsXvcBkmD1ak';
const SHEET_GID='0';
const URL_CSV_EXPORT=`https://docs.google.com/spreadsheets/d/${SHEET_ID}/export?format=csv&gid=${SHEET_GID}`;
const URL_EDIT_GOOGLE_SHEETS=`https://docs.google.com/spreadsheets/d/${SHEET_ID}/edit?usp=sharing`;
const STORAGE_KEY='catalogo_calculadora_multisservicos_v3';
const CONFIG_KEY='config_calculadora_multisservicos_v1';
const DADOS_FALLBACK=[
{id:1,categoria:'Impressão',nome:'Cartaz A3',tipoCalculo:'quantidade',preco:2.50,margem:20},
{id:2,categoria:'Impressão',nome:'Cartaz A2',tipoCalculo:'quantidade',preco:4.00,margem:20},
{id:3,categoria:'Vinil',nome:'Vinil Monomérico Impresso',tipoCalculo:'area_com_extras',preco:15.00,margem:25,permiteExtras:true},
{id:4,categoria:'Vinil',nome:'Vinil Monomérico Laminado',tipoCalculo:'area',preco:20.00,margem:25},
{id:5,categoria:'Fotografia',nome:'Sessão Fotográfica',tipoCalculo:'horas_fotografia',preco:170.00,margem:0},
{id:6,categoria:'Design',nome:'Design Gráfico',tipoCalculo:'tempo_design',preco:35.00,margem:10},
{id:7,categoria:'PVC',nome:'PVC 3mm',tipoCalculo:'pvc_tabela',preco:17.50,margem:15,opcoes:{so_pvc:17.50,pvc_vinil:27.50,pvc_uv:31.50}},
{id:8,categoria:'PVC',nome:'PVC 5mm',tipoCalculo:'pvc_tabela',preco:22.50,margem:15,opcoes:{so_pvc:22.50,pvc_vinil:32.50,pvc_uv:37.50}},
{id:9,categoria:'Cartões',nome:'Cartões Expressos',tipoCalculo:'quantidade_degrau',preco:48,margem:10,degraus:{100:48,250:65,500:95,1000:115}},
{id:10,categoria:'Cartões',nome:'Cartões Premium',tipoCalculo:'quantidade_degrau',preco:120,margem:10,degraus:{250:120,500:145,1000:195}}
];
const CONFIG_DEFAULT={empresaNome:'A sua empresa',empresaNif:'',empresaMorada:'',empresaEmail:'',empresaTelefone:'',validadeDias:15,mbway:'',iban:'',logo:''};
let produtos=[],origemDados='';let ultimoOrcamento=null;
const $=id=>document.getElementById(id);const existe=id=>!!$(id);
function clonar(o){return JSON.parse(JSON.stringify(o));}
function numero(v,p=0){const n=parseFloat(String(v??'').replace(/€/g,'').replace(/%/g,'').replace(/\s/g,'').replace(',','.'));return Number.isFinite(n)?n:p;}
function dinheiro(v){return Number(v||0).toLocaleString('pt-PT',{style:'currency',currency:'EUR'});}
function dataPT(d){return new Date(d+'T00:00:00').toLocaleDateString('pt-PT');}
function esc(s){return String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[m]));}
function mostrarEstado(t,erro=false){if(!existe('estadoApp'))return; $('estadoApp').textContent=t;$('estadoApp').classList.toggle('erro',erro);$('estadoApp').style.display='block';}
function carregarConfig(){try{return {...CONFIG_DEFAULT,...JSON.parse(localStorage.getItem(CONFIG_KEY)||'{}')}}catch{return {...CONFIG_DEFAULT}}}
function guardarConfig(c){localStorage.setItem(CONFIG_KEY,JSON.stringify(c));}
function parseCSV(texto){const linhas=[];let linha=[],campo='',aspas=false;for(let i=0;i<texto.length;i++){const c=texto[i],p=texto[i+1];if(c==='"'){if(aspas&&p==='"'){campo+='"';i++;}else aspas=!aspas;}else if(c===','&&!aspas){linha.push(campo);campo='';}else if((c==='\n'||c==='\r')&&!aspas){if(c==='\r'&&p==='\n')i++;linha.push(campo);if(linha.some(x=>String(x).trim()!==''))linhas.push(linha);linha=[];campo='';}else campo+=c;}linha.push(campo);if(linha.some(x=>String(x).trim()!==''))linhas.push(linha);return linhas;}
function norm(v){return String(v||'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'');}
function campo(obj,nomes,p=''){for(const n of nomes){const k=Object.keys(obj).find(x=>norm(x)===norm(n));if(k&&obj[k]!==undefined&&obj[k]!=='')return obj[k];}return p;}
function jsonCampo(v,p){if(!v)return p;try{return JSON.parse(v)}catch{return p}}
function criarOpcoesPvc(preco){return{so_pvc:preco,pvc_vinil:+(preco*1.5).toFixed(2),pvc_uv:+(preco*1.8).toFixed(2)}}
function criarDegraus(preco){return{100:preco,250:+(preco*1.35).toFixed(2),500:+(preco*1.9).toFixed(2),1000:+(preco*2.5).toFixed(2)}}
function prepararItem(i){const p={...i,id:parseInt(i.id,10),preco:numero(i.preco),margem:numero(i.margem),permiteExtras:Boolean(i.permiteExtras)||i.tipoCalculo==='area_com_extras'};if(p.tipoCalculo==='pvc_tabela'&&!p.opcoes)p.opcoes=criarOpcoesPvc(p.preco);if(p.tipoCalculo==='quantidade_degrau'&&!p.degraus)p.degraus=criarDegraus(p.preco);return p;}
function csvParaProdutos(csv){if(!csv||csv.includes('<!DOCTYPE'))throw new Error('A resposta não é CSV. Publique a folha ou confirme permissões.');const m=parseCSV(csv);if(m.length<2)throw new Error('CSV sem dados.');const h=m[0].map(x=>String(x).trim()),out=[];for(let i=1;i<m.length;i++){const obj={};h.forEach((hh,idx)=>obj[hh||`coluna_${idx}`]=(m[i][idx]||'').trim());const id=parseInt(campo(obj,['id','codigo','código'],String(i)),10);const categoria=campo(obj,['categoria','cat'],'Geral');const nome=campo(obj,['nome','produto','servico','serviço','produto/servico','produto serviço'],'Item '+id);const tipoCalculo=campo(obj,['tipoCalculo','tipo_calculo','tipo','calculo','cálculo'],'quantidade');const preco=numero(campo(obj,['preco','preço','precoBase','valor'],'0'));const margem=numero(campo(obj,['margem','margem%'],'0'));const item={id,categoria,nome,tipoCalculo,preco,margem,iva:0,permiteExtras:tipoCalculo==='area_com_extras'||/^(sim|true|1)$/i.test(campo(obj,['permiteExtras','extras'],''))};if(tipoCalculo==='pvc_tabela')item.opcoes=jsonCampo(campo(obj,['opcoes','opções','pvc','tabelaPvc'],''),criarOpcoesPvc(preco));if(tipoCalculo==='quantidade_degrau')item.degraus=jsonCampo(campo(obj,['degraus','escaloes','escalões','quantidades'],''),criarDegraus(preco));if(id&&nome)out.push(item);}if(!out.length)throw new Error('Sem produtos válidos.');return out;}
async function carregarDadosOnline(){const local=localStorage.getItem(STORAGE_KEY);if(local){try{produtos=JSON.parse(local).map(prepararItem);origemDados='local';mostrarEstado('A usar catálogo local/importado guardado neste navegador.');return produtos;}catch{localStorage.removeItem(STORAGE_KEY)}}try{const r=await fetch(URL_CSV_EXPORT+'&cachebust='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);produtos=csvParaProdutos(await r.text()).map(prepararItem);origemDados='google';mostrarEstado(`Dados carregados do Google Sheets: ${produtos.length} itens.`);return produtos;}catch(e){produtos=clonar(DADOS_FALLBACK).map(prepararItem);origemDados='fallback';mostrarEstado('Não consegui ler o Google Sheets. A usar dados de exemplo/fallback.',true);console.warn(e);return produtos;}}
function guardarLocal(){localStorage.setItem(STORAGE_KEY,JSON.stringify(produtos));origemDados='local';mostrarEstado('Alterações guardadas localmente neste navegador.');}
function desenharMenuDropdown(sel){if(!sel)return;const atual=sel.value;const termo=(existe('pesquisaProduto')?$('pesquisaProduto').value:'').toLowerCase().trim();sel.innerHTML='<option value="">-- Selecione uma Opção --</option>';const lista=produtos.filter(p=>!termo||`${p.categoria} ${p.nome}`.toLowerCase().includes(termo));[...new Set(lista.map(p=>p.categoria||'Geral'))].forEach(cat=>{const og=document.createElement('optgroup');og.label=cat;lista.filter(p=>(p.categoria||'Geral')===cat).forEach(p=>{const o=document.createElement('option');o.value=p.id;o.textContent=p.nome+(origemDados==='fallback'?' (exemplo)':'');og.appendChild(o)});sel.appendChild(og)});if([...sel.options].some(o=>o.value===atual))sel.value=atual;}
function esconderDinamicos(){document.querySelectorAll('.dinamico').forEach(p=>p.style.display='none');if(existe('extrasVinil'))$('extrasVinil').style.display='none';if(existe('blocoResultado'))$('blocoResultado').style.display='none';}
function ajustarFormulario(){esconderDinamicos();const prod=produtos.find(p=>p.id==($('cmbProduto')?.value||''));if(!prod)return;if(prod.tipoCalculo==='area'||prod.tipoCalculo==='area_com_extras'){$('painelArea').style.display='block';if(prod.permiteExtras)$('extrasVinil').style.display='block';}else if(prod.tipoCalculo==='quantidade')$('painelQuantidade').style.display='block';else if(prod.tipoCalculo==='horas_fotografia')$('painelHoras').style.display='block';else if(prod.tipoCalculo==='tempo_design')$('painelDesign').style.display='block';else if(prod.tipoCalculo==='pvc_tabela')$('painelPvc').style.display='block';else if(prod.tipoCalculo==='quantidade_degrau'){$('painelCartoes').style.display='block';const s=$('cmbQuantidadeCartoes');s.innerHTML='';Object.entries(prod.degraus||criarDegraus(prod.preco)).forEach(([q,v])=>{const o=document.createElement('option');o.value=v;o.dataset.qtd=q;o.textContent=`${q} unidades = ${dinheiro(v)}`;s.appendChild(o);});}}
function calcularPrecoFinal(){const prod=produtos.find(p=>p.id==($('cmbProduto')?.value||''));if(!prod)return alert('Por favor, selecione um produto ou serviço.');let base=0,detalhe='',extras=[];if(prod.tipoCalculo==='area'||prod.tipoCalculo==='area_com_extras'){const larg=numero($('largura').value),alt=numero($('altura').value);if(larg<=0||alt<=0)return alert('Insira medidas válidas.');if(larg>1.27&&alt>1.27)alert('⚠️ Atenção: largura e altura excedem 1,27 m. O trabalho terá emendas.');const area=larg*alt;base=area*prod.preco;detalhe=`${area.toFixed(2)} m² × ${dinheiro(prod.preco)}`;if(prod.permiteExtras){if($('chkAplicar').checked){base+=area*prod.preco*.60;extras.push('Aplicação de vinil')}if($('chkCorte').checked){base+=area*10;extras.push('Corte')}if($('chkPelicula').checked){base+=area*8;extras.push('Película transferência')}if($('chkLaminacao').checked){base+=area*15;extras.push('Laminação')}}}else if(prod.tipoCalculo==='quantidade'){const q=parseInt($('quantidade').value,10)||0;if(q<=0)return alert('A quantidade deve ser igual ou superior a 1.');base=q*prod.preco;detalhe=`${q} un. × ${dinheiro(prod.preco)}`;}else if(prod.tipoCalculo==='horas_fotografia'){const h=parseInt($('horasFotografia').value,10)||0;if(h<=0)return alert('Insira horas válidas.');let vh=prod.preco;if(h>=6)vh=prod.preco*.70;else if(h>=3)vh=prod.preco*.80;base=h*vh;detalhe=`${h} hora(s) × ${dinheiro(vh)}`;}else if(prod.tipoCalculo==='tempo_design'){base=numero($('tempoDesign').value);detalhe=$('tempoDesign').selectedOptions[0]?.textContent||'Bloco de design';}else if(prod.tipoCalculo==='pvc_tabela'){const acab=$('tipoAcabamentoPvc').value,precoM2=(prod.opcoes||{})[acab]||prod.preco,larg=numero($('pvcLargura').value),alt=numero($('pvcAltura').value);if(larg<=0||alt<=0)return alert('Insira medidas válidas.');const area=larg*alt;base=area*precoM2;detalhe=`PVC ${area.toFixed(2)} m² × ${dinheiro(precoM2)}/m²`;}else if(prod.tipoCalculo==='quantidade_degrau'){base=numero($('cmbQuantidadeCartoes').value);detalhe=`Lote de ${$('cmbQuantidadeCartoes').selectedOptions[0]?.dataset.qtd||''} unidades`;}const total=base*(1+(prod.margem/100));ultimoOrcamento={produto:prod.nome,detalhe,extras,total,subtotal:total,base,clienteNome:$('clienteNome')?.value||'',clienteNif:$('clienteNif')?.value||'',data:$('dataOrcamento')?.value||new Date().toISOString().slice(0,10)};$('resNomeProduto').textContent=prod.nome+(origemDados==='fallback'?' (exemplo)':'');$('resDetalhe').textContent=detalhe+(extras.length?' | '+extras.join(', '):'');$('resSubtotal').textContent=dinheiro(total);$('resIva').textContent='0,00 € (Art.º 53º)';$('resTotal').textContent=dinheiro(total);$('blocoResultado').style.display='block';gerarOrcamentoPrint();}
function qrData(total,cfg){const linhas=[];if(cfg.mbway)linhas.push(`MB WAY: ${cfg.mbway}`);if(cfg.iban)linhas.push(`IBAN: ${cfg.iban}`);linhas.push(`Valor: ${dinheiro(total)}`);return linhas.join('\n');}
function gerarOrcamentoPrint(){if(!existe('orcamentoPrint')||!ultimoOrcamento)return;const cfg=carregarConfig();const validade=new Date(ultimoOrcamento.data+'T00:00:00');validade.setDate(validade.getDate()+Number(cfg.validadeDias||15));const qr=qrData(ultimoOrcamento.total,cfg);const qrUrl='https://api.qrserver.com/v1/create-qr-code/?size=140x140&data='+encodeURIComponent(qr);$('orcamentoPrint').innerHTML=`<div class="print-header"><div>${cfg.logo?`<img class="print-logo" src="${cfg.logo}" alt="Logótipo">`:''}<h2>${esc(cfg.empresaNome)}</h2><div>${esc(cfg.empresaMorada)}</div><div>${cfg.empresaNif?'NIF: '+esc(cfg.empresaNif):''}</div><div>${esc(cfg.empresaEmail)} ${esc(cfg.empresaTelefone)}</div></div><div class="print-title"><h1>Orçamento</h1><div>Data: ${dataPT(ultimoOrcamento.data)}</div><div>Válido até: ${validade.toLocaleDateString('pt-PT')}</div></div></div><div class="print-grid"><div class="print-box"><strong>Cliente</strong><br>${esc(ultimoOrcamento.clienteNome||'Consumidor final')}<br>${ultimoOrcamento.clienteNif?'NIF: '+esc(ultimoOrcamento.clienteNif):''}</div><div class="print-box"><strong>Condições</strong><br>Isento de IVA ao abrigo do Art.º 53.º do CIVA.<br>Valores sujeitos a confirmação após adjudicação.</div></div><table class="print-table"><thead><tr><th>Descrição</th><th>Total</th></tr></thead><tbody><tr><td><strong>${esc(ultimoOrcamento.produto)}</strong><br>${esc(ultimoOrcamento.detalhe)}${ultimoOrcamento.extras.length?'<br>Extras: '+esc(ultimoOrcamento.extras.join(', ')):''}</td><td>${dinheiro(ultimoOrcamento.total)}</td></tr></tbody></table><div class="print-total">Total: ${dinheiro(ultimoOrcamento.total)}</div><div class="print-footer"><div><strong>Pagamento</strong><br>${cfg.mbway?'MB WAY: '+esc(cfg.mbway)+'<br>':''}${cfg.iban?'IBAN: '+esc(cfg.iban):''}<br><br><span class="small">Assinatura / Carimbo: ________________________________</span></div><div class="print-qr"><img src="${qrUrl}" alt="QR Code"><div class="small">QR Code para dados de pagamento</div></div></div>`;}
function imprimirOrcamento(){if(!ultimoOrcamento)calcularPrecoFinal();gerarOrcamentoPrint();window.print();}
function preencherConfigBackend(){if(!existe('cfgEmpresaNome'))return;const c=carregarConfig();$('cfgEmpresaNome').value=c.empresaNome;$('cfgEmpresaNif').value=c.empresaNif;$('cfgEmpresaMorada').value=c.empresaMorada;$('cfgEmpresaEmail').value=c.empresaEmail;$('cfgEmpresaTelefone').value=c.empresaTelefone;$('cfgValidadeDias').value=c.validadeDias;$('cfgMbway').value=c.mbway;$('cfgIban').value=c.iban;}
function guardarConfiguracaoEmpresa(){const salvar=(logo)=>{const c={empresaNome:$('cfgEmpresaNome').value||'A sua empresa',empresaNif:$('cfgEmpresaNif').value,empresaMorada:$('cfgEmpresaMorada').value,empresaEmail:$('cfgEmpresaEmail').value,empresaTelefone:$('cfgEmpresaTelefone').value,validadeDias:numero($('cfgValidadeDias').value,15),mbway:$('cfgMbway').value,iban:$('cfgIban').value,logo:logo??carregarConfig().logo};guardarConfig(c);alert('✅ Dados da empresa guardados.');};const f=$('cfgLogo')?.files?.[0];if(f){const r=new FileReader();r.onload=e=>salvar(e.target.result);r.readAsDataURL(f);}else salvar();}
function atualizarListaBackend(lista){if(!lista)return;lista.innerHTML='';if(!produtos.length){lista.innerHTML='<li>Nenhum item.</li>';return;}produtos.forEach(p=>{let preco=p.tipoCalculo==='pvc_tabela'?'Preço por m² múltiplo':p.tipoCalculo==='quantidade_degrau'?'Escalonado por pacotes':dinheiro(p.preco);const li=document.createElement('li');li.innerHTML=`<div><span class="badge">${esc(p.categoria)}</span><span class="badge">${esc(p.tipoCalculo)}</span><small>ID: ${p.id}</small><br><strong>${esc(p.nome)}</strong><br><small>Valor: ${preco} | Margem: ${p.margem}% | Isento Art.º 53º</small></div><div class="acoes"><button class="btn-acao edit" onclick="abrirEdicao(${p.id})">✏️ Editar</button><button class="btn-acao dup" onclick="duplicarItem(${p.id})">📋 Duplicar</button><button class="btn-acao del" onclick="apagarItem(${p.id})">🗑️ Apagar</button></div>`;lista.appendChild(li);});}
function adicionarItem(){const categoria=$('novoCategoria').value.trim(),nome=$('novoNome').value.trim(),tipo=$('novoTipo').value,preco=numero($('novoPreco').value,NaN),margem=numero($('novaMargem').value,0);if(!categoria||!nome||!Number.isFinite(preco)||preco<0)return alert('Preencha categoria, nome e preço válido.');const id=produtos.reduce((m,p)=>Math.max(m,p.id),0)+1;const item=prepararItem({id,categoria,nome,tipoCalculo:tipo,preco,margem,iva:0,permiteExtras:tipo==='area_com_extras'});produtos.push(item);guardarLocal();atualizarListaBackend($('listaProdutos'));['novoCategoria','novoNome','novoPreco'].forEach(id=>$ (id).value='');$('novaMargem').value='0';alert('✅ Item adicionado.');}
function abrirEdicao(id){const p=produtos.find(x=>x.id===id);if(!p)return;$('editId').value=p.id;$('editCategoria').value=p.categoria;$('editNome').value=p.nome;$('editTipo').value=p.tipoCalculo;$('editPreco').value=p.preco;$('editMargem').value=p.margem;$('modalEdicao').classList.add('active');}
function salvarEdicao(){const id=parseInt($('editId').value,10),p=produtos.find(x=>x.id===id);if(!p)return;const preco=numero($('editPreco').value,NaN);if(!$('editCategoria').value.trim()||!$('editNome').value.trim()||!Number.isFinite(preco))return alert('Dados inválidos.');Object.assign(p,prepararItem({id,categoria:$('editCategoria').value.trim(),nome:$('editNome').value.trim(),tipoCalculo:$('editTipo').value,preco,margem:numero($('editMargem').value,0),iva:0,permiteExtras:$('editTipo').value==='area_com_extras'}));guardarLocal();atualizarListaBackend($('listaProdutos'));fecharModal();alert('✅ Item atualizado.');}
function apagarItem(id){const p=produtos.find(x=>x.id===id);if(!p||!confirm(`Apagar "${p.nome}"?`))return;produtos=produtos.filter(x=>x.id!==id);guardarLocal();atualizarListaBackend($('listaProdutos'));}
function duplicarItem(id){const p=produtos.find(x=>x.id===id);if(!p)return;const novo=clonar(p);novo.id=produtos.reduce((m,x)=>Math.max(m,x.id),0)+1;novo.nome+=' (cópia)';produtos.push(novo);guardarLocal();atualizarListaBackend($('listaProdutos'));}
function fecharModal(){if(existe('modalEdicao'))$('modalEdicao').classList.remove('active');}
function exportarJSON(){const blob=new Blob([JSON.stringify(produtos,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='backup_produtos_'+new Date().toISOString().slice(0,10)+'.json';a.click();URL.revokeObjectURL(url);}
function importarJSON(input){const f=input.files[0];if(!f)return;const r=new FileReader();r.onload=e=>{try{const d=JSON.parse(e.target.result);if(!Array.isArray(d))throw new Error('JSON não é lista.');produtos=d.map(prepararItem);guardarLocal();atualizarListaBackend($('listaProdutos'));alert('✅ Importado.');}catch(err){alert('Erro: '+err.message)}};r.readAsText(f);input.value='';}
async function sincronizarGoogleSheets(){if(!confirm('Recarregar dados do Google Sheets? Alterações locais serão ignoradas se limpar o catálogo local.'))return;localStorage.removeItem(STORAGE_KEY);await carregarDadosOnline();atualizarListaBackend($('listaProdutos'));desenharMenuDropdown($('cmbProduto'));}
function limparCatalogoLocal(){if(!confirm('Limpar catálogo guardado neste navegador e voltar ao Google Sheets/fallback?'))return;localStorage.removeItem(STORAGE_KEY);location.reload();}
function abrirGoogleSheets(){window.open(URL_EDIT_GOOGLE_SHEETS,'_blank');}
async function inicializar(){if(existe('dataOrcamento'))$('dataOrcamento').value=new Date().toISOString().slice(0,10);preencherConfigBackend();await carregarDadosOnline();desenharMenuDropdown($('cmbProduto'));atualizarListaBackend($('listaProdutos'));}
document.addEventListener('DOMContentLoaded',inicializar);
